source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'MJRefresh'
pod 'SDAutoLayout', '~> 1.52'
pod 'SDCycleScrollView','~> 1.61'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'TTTAttributedLabel'
pod 'DateTools'
pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
pod 'DZNEmptyDataSet’

